<?xml version="1.0"?>
<robot name="firefighter" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- TODO: part of test_robot.urdf -->

    <xacro:property name="pi" value="3.1415926" />
    <xacro:property name="width" value="0.2" />
    <xacro:property name="body_length" value="0.6" />
    <xacro:property name="leg_length" value="0.6" />

    <xacro:macro name="default_inertial" params="mass">
        <inertial>
            <mass value="${mass}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
    </xacro:macro>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${width}" length="${body_length}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${width}" length="${body_length}"/>
            </geometry>
        </collision>
        <xacro:default_inertial mass="10"/>
    </link>

<!--  Use a name prefix to get two similarly named objects.  -->
<!--  Use math to calculate joint origins.  -->
<!--  Using a reflect parameter, and setting it to 1 or -1.  -->
    <xacro:macro name="leg" params="prefix reflect">
        <link name="${prefix}_leg">
            <visual>
                <geometry>
                    <box size="${leg_length} 0.1 0.2"/>
                </geometry>
                <origin xyz="0 0 -${leg_length/2}" rpy="0 ${pi/2} 0"/>
                <material name="white"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${leg_length} 0.1 0.2"/>
                </geometry>
                <origin xyz="0 0 -${leg_length/2}" rpy="0 ${pi/2} 0"/>
            </collision>
            <xacro:default_inertial mass="10"/>
        </link>

        <joint name="base_to_${prefix}_leg" type="fixed">
            <parent link="base_link"/>
            <child link="${prefix}_leg"/>
            <origin xyz="0 ${reflect*(width+.02)} 0.25" />
        </joint>
        <!-- A bunch of stuff cut -->
    </xacro:macro>
    <xacro:leg prefix="right" reflect="1" />
    <xacro:leg prefix="left" reflect="-1" />

</robot>